env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:jsonc/recommended-with-json5
  - plugin:jsonc/prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
