env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/recommended"
  - plugin:jsonc/recommended-with-json5
  - plugin:jsonc/prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {}
overrides:
  - files:
      - "*.json"
      - "*.json5"
      - "*.jsonc"
    parser: jsonc-eslint-parser
